/**
 * Generated by scripts/sync-api-workspace-acl.mjs from public/data — do not edit.
 * Lives under server/impl/ (outside api/) so Vercel does not treat it as a Serverless route.
 */
export const WORKSPACE_MANIFEST_MARKET_ORDER = ["AT","AU","BE","CA","CH","CZ","DE","ES","FR","IT","NL","PL","PT","SK","SL","UA","UK"] as readonly string[];

export const SEGMENT_TO_MARKETS: Record<string, readonly string[]> = {
  "LIOM": ["AU","UK","DE","CA","FR","IT","ES","PL"] as const,
  "IOM": ["CH","AT","NL","BE","PT","CZ","SK","SL","UA"] as const
};
